workflows:
  build-ios:
    name: Build iOS IPA (manual zip)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean
        script: flutter clean
      - name: Get packages
        script: flutter pub get
      - name: Build for iOS device (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Crear IPA manualmente
        script: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Cotizacion.ipa Payload
    artifacts:
      - Cotizacion.ipa

      